[package]
name = "adapter"
version = "0.1.0"
edition.workspace = true

[dependencies]
kernel.workspace = true
shared.workspace = true
async-trait.workspace = true
sqlx.workspace = true
derive-new.workspace = true
