[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel.workspace = true
registry.workspace = true
axum.workspace = true
serde.workspace = true
anyhow.workspace = true
uuid.workspace = true
thiserror.workspace = true
